config/routes.rb
FamousAPI::Application.routes.draw do

  resources :group_members


  resources :place_groups


  resources :subscriptions


  resources :referrals


  resources :stored_users


  resources :smsgateways

  resources :ratings

  resources :comments

  # resources :candidates do
  #   get 'candidates/:candidate_id/comments', to: 'candidates#comments'
  # end
  
  resources :candidates do
    resources :comments
  end

  resources :settings


  resources :welcomes
  root to: 'welcomes#index'

   # static pages
  match '/faqs' => 'welcomes#faqs'
  match '/pricing' => 'welcomes#pricing'
  
  put 'group_members/:id/confirm' => 'group_members#confirm', :as => 'confirm_member'

  devise_scope :user do
    #root to: "devise/registrations#new"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :invitations => 'users/invitations' }

  resources :users do
    resources :notifications
    resources :place_groups do
      resources :group_members
    end
  end

  get 'discovery', to: :discovery, controller: 'place_groups'
  put 'group_action', to: :group_action, controller: 'group_members'

  resources :place_groups do
    resources :group_members
  end
  
  namespace :api, defaults: {format: 'json'} do
    devise_for :users

    get 'feeds' => 'feeds#index'
    get 'search' => 'search#index'
    get 'search/people' => 'search#people'
    get 'search/company' => 'search#company'
    get 'search/competition' => 'search#competition'
    get 'search/latest' => 'search#latest'

    match "users/social_login" => "users#social_login", :via => :post

    resources :devices

    resources :competitions do
      get 'top', on: :collection
      get 'suggested', on: :collection
      get 'search', on: :collection
      get 'nominees', on: :member
      post ':id/nominees', to: "nominees#create"
      resources :competition_qualifications do
        get 'search', on: :collection
      end
      resources :prizes
      resources :nominees do
        get 'ranking', on: :collection
        resources :nominee_testimonies, :path => :testimonies
        resources :videos do
          resources :competition_video_comments do
            resources :ratings
          end
        end
      end
    end

    resources :jobs do
      post 'apply', to: 'jobs#apply'
      post 'refer', to: 'jobs#refer'
      post 'invite', to: 'jobs#invite'
      get 'applied', on: :collection
      get 'candidates', to: 'jobs#candidates'
      get 'candidates/short_listed', to: 'jobs#short_listed'
      get 'candidates/candidate_short_listed', to: 'jobs#candidate_short_listed'
      get 'candidates/short_listed/accepted_schedule', to: 'jobs#accepted_schedule'
      get 'candidates/short_listed/re_schedule', to: 'jobs#re_schedule'
      post 'candidates/:candidate_id/short_list', to: 'jobs#short_list', as: :short_list_candidate
      post 'candidates/:candidate_id/accept_interview_schedule', to: 'jobs#accept_interview_schedule', as: :accept_interview_schedule
      post 'candidates/:candidate_id/reschedule_interview', to: 'jobs#reschedule_interview', as: :reschedule_interview
      post 'questions/:job_question_id/answer', to: 'jobs#answer', as: :answer
      post 'candidates/cancel_application', to: 'jobs#cancel_application', as: :cancel_application
      get 'search', on: :collection, as: :search
      post 'candidates/:candidate_id/promote_video_resource', to: 'jobs#promote_video_resource', as: :promote_video_resource
    end

    get 'users/:user_id/companies/following' => 'users#followingCompanies'
    get 'users/:user_id/followers' => 'users#followers'
    get 'users/:user_id/subscribed', to: 'jobs#subscribed'
    post 'users/:user_id/subscribe' => 'jobs#subscribe'
    get 'users/:user_id/following' => 'users#following'
    get 'users/:user_id/activities' => 'users#activities'
    get 'users/:user_id/companies/managed' => 'companies#managed'
    get 'users/:user_id/pending_permissions' => 'users#pending_permissions'
    get 'companies/:company_id/employees' => 'companies#employees'
    get 'users/:user_id/active_nominations' => 'users#active_nominations'
    get 'users/:user_id/inactive_nominations' => 'users#inactive_nominations'
    
    get 'place_groups/:place_id/members' => "place_groups#members"
    
    get 'users/:user_id/testimonies/gallery' => "testimonies#gallery"
    get 'users/:user_id/testimonies/testimonials' => "testimonies#testimonials"

    resources :activities do
      resources :comments
    end

    resources :users do
      get 'search', on: :collection
      get 'me', on: :collection
      get 'nearest', on: :collection
      get 'latest', on: :collection

      post 'follow', to: "users#follow"
      post 'unfollow', to: "users#unfollow"

      put 'featured_video', to: "registrations#featured_video"

      resources :companies do
        resources :company_testimonies
      end
      resources :interests do
        post 'permission', to: 'interests#permission'
        post 'allow', to: "interests#approve"
        post 'reject', to: "interests#reject"
      end
      resources :trainings do
        post 'permission', to: 'trainings#permission'
      end
      resources :videos do
        get 'mine', on: :collection
        post 'view', to: 'videos#updated_view_count'
        resources :comments
      end
      resources :professions do
        post 'permission', to: 'professions#permission'
      end
      resources :goals do
        post 'permission', to: 'goals#permission'
      end
      resources :videos do
        resources :comments
      end
      resources :testimonies do
        post 'allow', to: "testimonies#approve"
        post 'reject', to: "testimonies#reject"
        resources :videos
      end
      resources :awards do
          post 'allow', to: "testimonies#approve"
          post 'reject', to: "testimonies#reject"
          resources :videos
          resources :competitions
      end
      resources :documents
      resources :images
      resources :place_groups
      resources :notifications
    end

    resources :videos do
      post 'like', to: "videos#like"
      put 'unlike', to: "videos#unlike"
      get 'trending', on: :collection
      resources :comments
    end
    
    resources :qualifications do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :adjectives do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :stored_professions do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :locations do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :companies do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :stored_achievements do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :stored_testimonies do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :stored_trainings do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    resources :stored_company_cultures do
      get :autocomplete_name, :on => :collection
      get 'search', on: :collection
    end

    get 'companies/:id/followers' => 'companies#followers'

    resources :companies do
      get :autocomplete_name, :on => :collection
      post 'follow', to: "companies#follow"
      post 'unfollow', to: "companies#unfollow"

      resources :company_testimonies

      resources :company_branches

      resources :company_dream_jobs

      resources :company_cultures
    end


    post 'nominate', to: 'nominees#create'
    get 'users/:id', to: 'users#show'
    resources :keys, except: :show
    get 'keys/:name', to: 'keys#show'
  end

  resources :users do
    get :autocomplete_name, :on => :collection
    get 'latest', to: 'api#users#latest'
    get 'pending_permissions', to: 'api#users#pending_permissions'
  end

  resources :users, defaults: {format: 'html'} do
    resources :goals
    resources :trainings
    resources :qualifications
    resources :awards
    resources :testimonies
    resources :professions
    resources :interests
    resources :documents
    resources :companies
    resources :company_employees
  end

  get 'feeds', to: 'feeds#index'

  get 'search', to: 'search#index'

  get 'search/candidates', to: 'search#candidates'

  get 'dashboard', to: 'dashboard#index'

  resources :companies do
    get 'invite', to: 'companies#invite'
    get 'accept', to: 'companies#accept'
  end
  resources :professions
  resources :trainings
  resources :interests
  resources :testimonies
  resources :goals

  resources :videos do
    post 'view', to: 'videos#updated_view_count'
  end

  resources :competitions, defaults: {format: 'html'} do
    get :autocomplete_name, :on => :collection
    resources :nominees
  end

  get 'trending', to: 'site#trending'

  resources :jobs do
    post 'apply', to: 'jobs#apply'
    get 'answer', to: 'jobs#answer'
    post 'post_answer', to: 'jobs#post_answer', as: :answer
    get :autocomplete_position, :on => :collection
  end
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  include PublicActivity::Model
  tracked
  attr_accessible :company_id, :description, :end_date, :name, :prize_id, :start_date, :user_id, :year, :superlative, :location, :poster, :poster_file_name, :is_private
  has_many :nominees
  has_many :competitionQualifications
  acts_as_followable

    has_attached_file :poster,
           :styles => { :medium => "x300", :thumb => "x100" },
           :storage => :s3,
           :s3_permissions => :private,
           :s3_credentials => "#{Rails.root}/config/aws.yml"
  	do_not_validate_attachment_file_type :poster
  
  def poster_url
        poster.url(:medium)
  end

end

app/helpers/api/competitions_helper.rb
module Api::CompetitionsHelper
      def competitionJSONResponse(competition)
           nom = (Nominee.joins(:counter).where(competition_id: competition.id).order('rand()').limit(1))

            video = Video.where(id: nom.pluck(:video_id))
            user = User.where(id: competition.user_id).limit(1)
            nominated_by_name = User.select('name').where(id: video.pluck(:created_by)).limit(1)
            nominated_by_id = User.select('id').where(id: video.pluck(:created_by)).limit(1)
            leading_nominee_by_name = User.select('name').where(id: video.pluck(:user_id)).limit(1)
            contest = Competition.where(id: nom.pluck(:competition_id)).limit(1)
            company = Company.where(id: competition.company_id)
            comments = CompetitionVideoComment.where(video_id: nom.pluck(:video_id), competition_id: competition.id)
            nominees = Nominee.where(competition_id: competition.id)

            competition[:nominee_id] = nom.pluck(:nominee_id)[0]
            competition[:nominee_name] = leading_nominee_by_name.pluck(:name)[0]
            competition[:video] = video.as_json(:methods => [:payload_url, :payload_mobile_url, :payload_thumb_url])
            competition[:stars_count] = nom.pluck(:votes)[0]
            competition[:nominated_by_name] = nominated_by_name.pluck(:name)[0]
            competition[:nominated_by_id] = nominated_by_id.pluck(:id)[0]
            competition[:views_count] = video.pluck(:views_count)[0]
            competition[:comments_count] = comments.count
            competition[:poster_url] = :poster_url
            competition[:facebook_share_url] = competition_url(competition.id)
            competition[:nominees_count] = nominees.count

            if !competition.company_id.nil?
                  competition[:sponsor_type] = "Company"
                  competition[:sponsor] = company.as_json(:methods => [:payload_url], :only => [:id, :name])[0]
            else
                  competition[:sponsor_type] = "User"
                  competition[:sponsor] = user.as_json(:methods => [:avatar_url], :only => [:id, :name])[0]
            end
            
            competition[:title] = competition.superlative.to_s() + " " + 
                                    competition.name.to_s() + " in " + 
                                    competition.location.to_s() + " for " + 
                                    competition.year.to_s()
            return competition
	end

      def competitionQualificationsString(competition)
            sq = []
            CompetitionQualification.where(competition_id: competition.id).each do | q |
                  sq << q.name
            end
            return sq
      end

      def competitionTitle(competition)
            return competition.superlative.to_s() + " " + competition.name.to_s() + " in  " + competition.location.to_s() + " for " + competition.year.to_s()
      end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
      def competitionJSONResponse(competition)
	     nom = (Nominee.joins(:counter).where(competition_id: competition.id).order("votes DESC").limit(1))

            video = Video.where(id: nom.pluck(:video_id))
            user = User.where(id: competition.user_id).limit(1)
            nominated_by_name = User.select('name').where(id: video.pluck(:created_by)).limit(1)
            nominated_by_id = User.select('id').where(id: video.pluck(:created_by)).limit(1)
            leading_nominee_by_name = User.select('name').where(id: video.pluck(:user_id)).limit(1)
            contest = Competition.where(id: nom.pluck(:competition_id)).limit(1)
            company = Company.where(id: competition.company_id)
            comments = CompetitionVideoComment.where(video_id: nom.pluck(:video_id), competition_id: competition.id)
            competition[:nominee_id] = nom.pluck(:nominee_id)[0]
            competition[:nominee_name] = leading_nominee_by_name.pluck(:name)[0]
            competition[:video] = video.as_json(:methods => [:payload_url, :payload_mobile_url, :payload_thumb_url])
            competition[:stars_count] = nom.pluck(:votes)[0]
            competition[:nominated_by_name] = nominated_by_name.pluck(:name)[0]
            competition[:nominated_by_id] = nominated_by_id.pluck(:id)[0]
            competition[:views_count] = 0
            competition[:comments_count] = comments.count
            competition[:poster_url] = :poster_url
            if !competition.company_id.nil?
                  competition[:sponsor_type] = "Company"
                  competition[:sponsor] = company.as_json(:methods => [:payload_url], :only => [:id, :name])[0]
            else
                  competition[:sponsor_type] = "User"
                  competition[:sponsor] = user.as_json(:methods => [:avatar_url], :only => [:id, :name])[0]
            end
            
            competition[:title] = competition.superlative.to_s() + " " + 
                                    competition.name.to_s() + " in " + 
                                    competition.location.to_s() + " for " + 
                                    competition.year.to_s()
            return competition
	end

      def competitionQualificationsString(competition)
            sq = []
            CompetitionQualification.where(competition_id: competition.id).each do | q |
                  sq << q.name
            end
            return sq
      end

      def competitionTitle(competition)
            return competition.superlative.to_s() + " " + competition.name.to_s() + " in  " + competition.location.to_s() + " for " + competition.year.to_s()
      end
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :prize_id %><br />
    <%= f.number_field :prize_id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<section class="content-section video-section">
  <div class="pattern-overlay">
  <!-- https://www.youtube.com/watch?v=fdJc1_IBKJA -->
  <a id="bgndVideo" class="player" data-property="{videoURL:'http://youtu.be/zk5gWVftERI',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
            <center>
                <%= form_tag("/competitions", method: "get") do %>
                    <div class="input-group input-group-lg col-md-8">
                        <input type="text" class="form-control" placeholder="Search for a competition" aria-describedby="sizing-addon1" name="q">
                        <span class="input-group-btn">
                            <input type="submit" class="btn btn-default" value="search"> 
                        </span>
                    </div>
                <% end %>
            </center>
       </div>
      </div>
    </div>
  </div>
</section>

<div class="row" style="margin-top:80px">
    <div class="col-md-12">
        <% @competitions.each do |competition| %>
                <%= link_to competition do %>
                <div class="col-sm-4 col-md-4 col-lg-4" style="height:550px;overflow:hidden;">
                    <div class="thumbnail">
                        <center>
                        <% if competition.video[0] %>
                            <video height="350" controls>
                                <source src="<%= get_video_for_competition(competition)%>" type="video/mp4">
                            </video>
                        <% else %>
                            <%= image_tag(competition.poster_url, :width => "90%", :height => "350px")  %>
                        <% end %>
                        </center>
                        <div class="caption">
                            <h3><%= competition.title %></h3>
                        </div>
                        <p>
                            <div class="fb-share-button" data-href="<%= competition_url(competition.id) %>" data-layout="button"></div>

                        </p>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<div class="row" style="magrin-top:-50px; color: #FFF">
  <div class="col-md-12">
      <div class="jumbotron" style="background: url('http://teamn10sity.com/wp-content/uploads/2014/05/1802056.jpg') no-repeat">
        <h2><%= @competition.title %></h2>
          <p>
            <%= @competition.start_date %> - <%= @competition.end_date %>
          </p>
      </div>
      <div class="col-md-6 col-md-offset-3">
        <ol class="breadcrumb">
          <li><a href="<%= competitions_path %>">Competitions</a></li>
          <li class="active"><%= @competition.title %></li>
        </ol>
      </div>
      <% @nominees.each do |nominee| %>
        <div class="col-md-4" style="min-height:350px">
          <div class="media well" style="color: #474747">
            <center>
            <a href="<%= competition_nominee_url(nominee.competition_id, nominee.id) %>">
              <div class="media-left media-middle">
                  <video height="240" controls>
                    <source src="<%= nominee.video.payload.url(:mobile) %>" type="video/mp4">
                  </video>
                  <p><span><%= image_tag nominee.user.avatar.url, :class => "media-object profile_image", :style =>   "width:60px;height:60px;"%>
                    <h4 class="media-heading"><%= link_to nominee.nominated_user_name, controller: "users", action: "show", id: nominee.user_id %></h4></span></p>
                  <p>Nominated by: <%= link_to nominee.nominated_by_user, controller: "users", action: "show", id:  nominee.creator_id %></p>
              </div>
              <div class="media-body">
                <p>
                  comments <span class="badge">0</span> | 
                  stars <span class="badge">0</span> |
                  <div class="fb-share-button" data-href="<%= competition_nominee_url(nominee.competition_id, nominee.id) %>" data-layout="button"></div>
                </p>
              </div>
              </a>
            </center>
          </div>
        </div>
      <% end %>
  </div>
  <div class="row">
  </div>
</div>